apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: renomy-api
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: 'kong'
    cert-manager.io/cluster-issuer: 'test-selfsigned'
spec:
  rules:
    - host: api.projectx.kiratech.biz
      http:
        paths:
          - path: /*
            backend:
              serviceName: api-svc
              servicePort: 8080
