{{- if .Values.commonLabels }}
  ---
{{- end }}
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-stack-template-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace }}
      name: aws-creds
      key: credentials
