# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: logs-pv
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 100Mi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: '/Users/maurosala/Dev/github/renomy-app-template/logs'
