{{- if .Values.commonLabels }}
  ---
{{- end }}
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: renomy-db
  labels:
    backstage.io/kubernetes-id: renomy
spec:
  forProvider:
    region: eu-central-1
    allocatedStorage: 10
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t2.micro
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mariadb
    dbName: renomydb
    dbSecurityGroups: ['sg-0416e7746bfd24244', 'sg-095929f38f40a3f75', 'sg-0644099ca471426fa']
    engineVersion: '10.4.13'
    licenseModel: general-public-license
    masterUsername: {{ .Values.api.db.username | quote }}
    masterPasswordSecretRef:
      key: password
      name: rdsmariadbql-conn
      namespace: {{ .Release.Namespace }}
    multiAZ: false
    skipFinalSnapshotBeforeDeletion: true
    port: 3306
    publiclyAccessible: true
    storageEncrypted: false
    storageType: standard
  writeConnectionSecretToRef:
    name: rdsmariadbql-conn
    namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: aws-stack-template-provider
